#!/opt/apps/r/3.3.3/bin/Rscript
# Author: Hyung Joo Lee

# Usage: ./fitCentipede.R $FILE.Xlist $FILE.Y $NAME 2>$FILE.LOG
# $FILE.Xlist: file of ATAC-seq insertion tag around TF motif matches, generated by genCentipedeXlist.pl
# $FILE.Y: file of TF motif match annotation
# $NAME: name base of output files

library(CENTIPEDE)

args <- commandArgs(trailingOnly = TRUE)
file.xlist <- args[1]
file.y <- args[2]
output <- args[3]


# Read table from the files
TF_Inserts <- read.table(file = file.xlist, header = FALSE, sep = "\t")
TF_Anno <- read.table(file = file.y, header = FALSE, sep = "\t",
  col.names = c("chrom", "danRer10Start", "danRer10End", "PWMscore", "Strand", "ConsScore"))


# Prepare Xlist and Y of fitCentipede function
# You can inclulde or exclude conservation score
Xlist <- list( ATAC=as.matrix(TF_Inserts) )
Y <- cbind( rep(1, dim(TF_Anno)[1]), TF_Anno[,4], TF_Anno[,6])


# Run fitCentipede function
centFit <- fitCentipede(Xlist = Xlist, Y = Y)

TF_Anno <- cbind( TF_Anno, centFit$PostPr )
colnames(TF_Anno) <- c("chrom", "danRer10Start", "danRer10End", "PWMscore", "Strand", "ConsScore", "PostPr")
file.PostPr <- paste(output, "_PostPr.txt.gz", sep="")
write.table(TF_Anno, file = gzfile(file.PostPr), quote = F, sep = "\t", row.names = F, col.names = F)

file.footprint <- paste(output, "_footprint.txt", sep="")
write.table(centFit$LambdaParList[[1]], file = file.footprint, quote = F, row.names = F, col.names = F)

save.image( paste(output, ".rda", sep="") )

# Plot image of insert sites ranked by CENTIPEDE posteriors
#file.insertSites <- paste(output, "_insertSites.png", sep="")
#png(file.insertSites, 600,600, bg="transparent")
#imageCutSitesCombined(TF_Inserts[order(centFit$PostPr),])
#dev.off()

#cutoff <- dim(subset(TF_Anno, TF_Anno$PostPr>0.95))-1
#file.insertSites <- paste(output, "_insertSitesTop.png", sep="")
#png(file.insertSites, 600,600, bg="transparent")
#imageCutSitesCombined(TF_Inserts[order(centFit$PostPr),][dim(TF_Inserts)[1]-cutoff:dim(TF_Inserts)[1],])
#dev.off()


# Plot estimated footprint
#file.profile <- paste(output, "_footprint.png", sep="")
#png(file.profile, 600,600, bg="transparent")
#plotProfile( centFit$LambdaParList[[1]], Mlen=(dim(TF_Inserts)[2]-400)/2 )
#dev.off()

q()
